[features]
seeds = false

[programs.localnet]
orange_miner = "GrqZWXFvcFmn6c1iXpmWvTZGnzLVJPpkZUTLCQfSFPcM"

[programs.devnet]
orange_miner = "GrqZWXFvcFmn6c1iXpmWvTZGnzLVJPpkZUTLCQfSFPcM"

[programs.mainnet]
orange_miner = "GrqZWXFvcFmn6c1iXpmWvTZGnzLVJPpkZUTLCQfSFPcM"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/root/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
